name: psntools-env
channels:
  - conda-forge
dependencies:
  - python==3.7
  - pip
  - pip:
    - biopython==1.78
    - cycler==0.10.0
    - Cython==0.29.23
    - decorator==4.4.2
    - GridDataFormats==0.5.0
    - gsd==2.4.2
    - joblib==1.0.1
    - kiwisolver==1.3.1
    - matplotlib==3.3.4
    - MDAnalysis==1.1.1
    - mmtf-python==1.1.2
    - msgpack==1.0.2
    - networkx==2.5.1
    - numpy==1.20.3
    - pandas==1.1.5
    - Pillow==8.2.0
    - pyparsing==2.4.7
    - python-dateutil==2.8.1
    - pytz==2021.1
    - PyYAML==5.4.1
    - scipy==1.6.3
    - seaborn==0.11.1
    - six==1.16.0
    - threadpoolctl==2.1.0
    - tqdm==4.61.0